version: "3.8"

services:
  backend:
    container_name: node-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5203:5203"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: always
