name: Docker Image Build and Deploy - Backend

on:
  push:
    branches: [ "version1" ] # Updated branch
  pull_request:
    branches: [ "version1" ] # Updated branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t tsmsanket18/hrms_app_backend:latest .
          docker push tsmsanket18/hrms_app_backend:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.TEST1 }}" > TSMHRMS.pem
          chmod 600 TSMHRMS.pem
          ssh -o StrictHostKeyChecking=no -i TSMHRMS.pem ubuntu@ec2-44-196-49-134.compute-1.amazonaws.com << 'EOF'
            # Authenticate Docker
            sudo docker login -u tsmsanket18 -p ${{ secrets.DOCKER_PASSWORD }}
            
            # Pull the latest Docker image
            sudo docker pull tsmsanket18/hrms_app_backend:latest
            
            # Stop and remove the existing container (if any)
            sudo docker stop backend || true
            sudo docker rm backend || true
            
            # Run the new container with port mapping (5203:5203)
            sudo docker run -d --name backend -p 5203:5203 tsmsanket18/hrms_app_backend:latest
            
            # Clean up old images
            sudo docker image prune -af
          EOF
